name: PR Build

on: pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [8, 11]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
      - name: Build with Gradle
        run: ./gradlew clean check --no-daemon --stacktrace














#sudo: required :)
#language: java
#jdk:
#  - openjdk8
#  - openjdk11
#services:
#  - docker
#before_cache:
#  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
#  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
#cache:
#  directories:
#    - $HOME/.gradle/caches/
#    - $HOME/.gradle/wrapper/
#install: true
#script: ./gradlew clean check --no-daemon --stacktrace
